FROM ubuntu:20.04

# username
ARG uname=younghoon


# install sudo
RUN apt-get update && apt-get -y install sudo


# add user / sudoers
RUN adduser --disabled-password --shell /bin/bash --gecos "" ${uname}
RUN adduser ${uname} sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers


# change user
USER ${uname}
WORKDIR /home/${uname}


# install necessaries
RUN sudo apt-get update && sudo apt-get -y install curl
RUN sudo apt-get update && sudo apt-get -y install vim
RUN sudo apt-get update && sudo apt-get -y install git


# install node, npm
ADD install_node.sh .
RUN bash install_node.sh


# # Install Ruby and other prerequisites
RUN sudo apt-get update && sudo apt-get -y install ruby-full build-essential zlib1g-dev


# install jekyll
ADD install_jekyll.sh .
RUN bash install_jekyll.sh

